CREATE TABLE ALLUSERSTABLE( 
    USERNAME VARCHAR(50) NOT NULL, 
    PASSWORD VARCHAR(50) NOT NULL, 
    PRIMARY KEY (USERNAME) 
);

CREATE TABLE URLHITS( 
	USERNAME VARCHAR(50) NOT NULL, 
    LONGURL VARCHAR(500) NOT NULL, 
    SHORTURL VARCHAR(50) NOT NULL,
    HITS INT NOT NULL,
    PRIMARY KEY (USERNAME,LONGURL) 
);